{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iffly",
    "module": "redux",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "redux-0.0.2.aar",
          "url": "redux-0.0.2.aar",
          "size": 32448,
          "sha512": "5beda8e9f8795d2d168f79b57626805888a18bcfc7fae67fc0c871de0bfe1a3cd024aba4967cd8cb3b98b10a452886dacf5d1805e3627d042eed0c52e1322c96",
          "sha256": "e5d31d0538de708631ae56784df443f5f6afa76c08b5f7c60cd7621e3839a51f",
          "sha1": "97b47131b753fee6be9096e537338888b0168636",
          "md5": "3657781fec7a53c6b3ea493629eacfe3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "redux-0.0.2.aar",
          "url": "redux-0.0.2.aar",
          "size": 32448,
          "sha512": "5beda8e9f8795d2d168f79b57626805888a18bcfc7fae67fc0c871de0bfe1a3cd024aba4967cd8cb3b98b10a452886dacf5d1805e3627d042eed0c52e1322c96",
          "sha256": "e5d31d0538de708631ae56784df443f5f6afa76c08b5f7c60cd7621e3839a51f",
          "sha1": "97b47131b753fee6be9096e537338888b0168636",
          "md5": "3657781fec7a53c6b3ea493629eacfe3"
        }
      ]
    }
  ]
}
